### ISSUE TITLE
java.lang.IndexOutOfBoundsException: end index (-2147481323) must not be negative

### ISSUE THREAD

**Issue by boluoge** [apache/paimon-trino#63]
**I also encountered the same problem today, as mentioned in previous issuses. Is there a solution? Here is my abnormal information:**
2024-04-09T18:50:12.548+0800	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20240409_104939_00005_8j8ji.1 failed
java.lang.IndexOutOfBoundsException: end index (-2147481323) must not be negative
	at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:81)
	at io.airlift.slice.Slice.checkIndexLength(Slice.java:1302)
	at io.airlift.slice.Slice.setBytes(Slice.java:788)
	at io.airlift.slice.DynamicSliceOutput.writeBytes(DynamicSliceOutput.java:153)
	at io.trino.spi.block.VariableWidthBlockBuilder.writeBytes(VariableWidthBlockBuilder.java:245)
	at io.trino.spi.type.VarcharType.writeSlice(VarcharType.java:205)
	at io.trino.spi.type.VarcharType.writeSlice(VarcharType.java:199)
	at org.apache.paimon.trino.TrinoPageSourceBase.writeSlice(TrinoPageSourceBase.java:211)
	at org.apache.paimon.trino.TrinoPageSourceBase.appendTo(TrinoPageSourceBase.java:194)
	at org.apache.paimon.trino.TrinoPageSourceBase.nextPage(TrinoPageSourceBase.java:138)
	at org.apache.paimon.trino.TrinoPageSourceBase.lambda$getNextPage$0(TrinoPageSourceBase.java:119)
	at org.apache.paimon.trino.ClassLoaderUtils.runWithContextClassLoader(ClassLoaderUtils.java:30)
	at org.apache.paimon.trino.TrinoPageSourceBase.getNextPage(TrinoPageSourceBase.java:116)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_5bf98be____20240409_104157_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by JingsongLi** [comment]
@boluoge Can you provide more informantion? How to re-produce?

**Comment by boluoge** [comment]
> @boluoge Can you provide more informantion? How to re-produce?

Thank you for your reply. Based on your suggestion, I have upgraded the paimon trino to 0.6 and the issue has been resolved.
