### ISSUE TITLE
java.lang.IndexOutOfBoundsException: end index (-2147483499) must not be negative

### ISSUE THREAD

**Issue by cbwn123** [apache/paimon-trino#9]
paimon version : 0.5
trino version : 416

When I was executing the select statement, this exception occurred. I added some exception traps myself and output some information.
I found that the size in the VariableWidthBlockBuilder class will exceed the maximum value of int and become negative.

io.trino.spi.TrinoException: org.apache.paimon.table.source.KeyValueTableRead$RowDataRecordReader
	at org.apache.paimon.trino.TrinoPageSourceBase.nextPage(TrinoPageSourceBase.java:141)
	at org.apache.paimon.trino.TrinoPageSourceBase.lambda$getNextPage$0(TrinoPageSourceBase.java:114)
	at org.apache.paimon.trino.ClassLoaderUtils.runWithContextClassLoader(ClassLoaderUtils.java:30)
	at org.apache.paimon.trino.TrinoPageSourceBase.getNextPage(TrinoPageSourceBase.java:112)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:301)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_416____20230609_030235_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.spi.TrinoException: VariableWidthBlockBuilder{positionCount=54228272, size=2147483624}
Slice length :173,Slice value :资产计算状态为：1000,资产对effDate字段进行补充数据：Thu Oct 22 19:51:18 CST 2020,资产对expDate字段进行补充数据：Wed Jan 01 00:00:00 CST 3000,
	at org.apache.paimon.trino.TrinoPageSourceBase.writeSlice(TrinoPageSourceBase.java:215)
	at org.apache.paimon.trino.TrinoPageSourceBase.appendTo(TrinoPageSourceBase.java:193)
	at org.apache.paimon.trino.TrinoPageSourceBase.nextPage(TrinoPageSourceBase.java:134)
	... 16 more
Caused by: java.lang.IndexOutOfBoundsException: end index (-2147483499) must not be negative
	at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:81)
	at io.airlift.slice.Slice.checkIndexLength(Slice.java:1301)
	at io.airlift.slice.Slice.setBytes(Slice.java:788)
	at io.airlift.slice.DynamicSliceOutput.writeBytes(DynamicSliceOutput.java:152)
	at io.trino.spi.block.VariableWidthBlockBuilder.writeBytes(VariableWidthBlockBuilder.java:244)
	at io.trino.spi.type.VarcharType.writeSlice(VarcharType.java:220)
	at io.trino.spi.type.VarcharType.writeSlice(VarcharType.java:214)
	at org.apache.paimon.trino.TrinoPageSourceBase.writeSlice(TrinoPageSourceBase.java:212)
	... 18 more

**Comment by cbwn123** [comment]
This problem occurs when using the S3 protocol for Cloud storage, but it does not exist on HDFS

**Comment by nonggialiang** [comment]
Seems the problem also affect HDFS.

paimon version: 0.5
trino version: 366

org.apache.kyuubi.KyuubiSQLException: org.apache.kyuubi.KyuubiSQLException: Error operating ExecuteStatement: org.apache.kyuubi.KyuubiSQLException: Query 20240321_013910_05930_pedj6 failed: end index (-2147481042) must not be negative
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.engine.trino.TrinoStatement.getData$1(TrinoStatement.scala:104)
	at org.apache.kyuubi.engine.trino.TrinoStatement.$anonfun$execute$1(TrinoStatement.scala:111)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:173)
	at scala.collection.Iterator$$anon$15.hasNext(Iterator.scala:656)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement.$anonfun$executeStatement$1(ExecuteStatement.scala:135)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement.org$apache$kyuubi$engine$trino$operation$ExecuteStatement$$executeStatement(ExecuteStatement.scala:135)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement$$anon$1.run(ExecuteStatement.scala:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.engine.trino.operation.TrinoOperation$$anonfun$onError$1.$anonfun$applyOrElse$1(TrinoOperation.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.kyuubi.Utils$.withLockRequired(Utils.scala:435)
	at org.apache.kyuubi.operation.AbstractOperation.withLockRequired(AbstractOperation.scala:51)
	at org.apache.kyuubi.engine.trino.operation.TrinoOperation$$anonfun$onError$1.applyOrElse(TrinoOperation.scala:129)
	at org.apache.kyuubi.engine.trino.operation.TrinoOperation$$anonfun$onError$1.applyOrElse(TrinoOperation.scala:124)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement.org$apache$kyuubi$engine$trino$operation$ExecuteStatement$$executeStatement(ExecuteStatement.scala:189)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement$$anon$1.run(ExecuteStatement.scala:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kyuubi.KyuubiSQLException: Query 20240321_013910_05930_pedj6 failed: end index (-2147481042) must not be negative
	at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
	at org.apache.kyuubi.engine.trino.TrinoStatement.getData$1(TrinoStatement.scala:104)
	at org.apache.kyuubi.engine.trino.TrinoStatement.$anonfun$execute$1(TrinoStatement.scala:111)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:173)
	at scala.collection.Iterator$$anon$15.hasNext(Iterator.scala:656)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement.$anonfun$executeStatement$1(ExecuteStatement.scala:135)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at org.apache.kyuubi.engine.trino.operation.ExecuteStatement.org$apache$kyuubi$engine$trino$operation$ExecuteStatement$$executeStatement(ExecuteStatement.scala:135)
	... 6 more

**Comment by JingsongLi** [comment]
New version already fixed this issue.
